version: '3.3'

volumes:
  postgres_data:
  json_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./src/.env
    expose:
      - 5432

  redis:
    image: redis:latest
    restart: always
    expose:
      - 6379

  rabbit:
      restart: always
      image: "rabbitmq:3-management"
      volumes:
        - ./rabbitmq.conf:/etc/rabbitmq/rabbitmq.conf
      env_file:
        - ./src/.env
      ports:
        - "5672:5672"
        - "15672:15672"
  
  bot:
    build:
      context: ./src/
      dockerfile: Bot.Dockerfile
    restart: always
    volumes:
      - "json_data:/code/svc/handlers:rw"
    depends_on:
      - db
      - redis
    env_file:
      - ./src/.env

  beat:
    build:
      context: ./src/
      dockerfile: Beat.Dockerfile
    restart: always
    volumes:
      - "json_data:/code/svc/handlers:ro"
    depends_on:
      - db
      - rabbit
    env_file:
      - ./src/.env

  worker:
    build:
      context: ./src/
      dockerfile: Worker.Dockerfile
    restart: always
    volumes:
      - "json_data:/code/svc/handlers:ro"
    depends_on:
      - db
      - rabbit
    env_file:
      - ./src/.env
