version: '3.3'

volumes:
  postgres_data:

services:
  db:
    image: postgres:12.4
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env
    ports:
      - "5432:5432"
  
  redis:
    image: redis
    restart: always
    ports:
      - "6379:6379"

  redisinsight:
    image: redislabs/redisinsight:latest
    ports:
      - '8001:8001'
  
  rabbit:
      restart: always
      image: "rabbitmq:3-management"
      env_file:
        - ./.env
      ports:
        - "5672:5672"
        - "15672:15672"
  
  bot:
    build:
      context: ./src/
      dockerfile: Bot.Dockerfile
    restart: always
    depends_on:
      - db
      - redis
    env_file:
      - ./.env
  
  beat:
    build:
      context: ./src/
      dockerfile: Beat.Dockerfile
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
      - bot
    env_file:
      - ./.env
  
  worker:
    build:
      context: ./src/
      dockerfile: Worker.Dockerfile
    restart: always
    depends_on:
      - db
      - redis
      - rabbit
      - bot
    env_file:
      - ./.env